### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by AaronLasseigne** [dallasrb/dallasrb.github.io#3]
We need a logo. Several ideas have been kicked around in the mailing group. Let's finalize the discussion here.

**Comment by zorab47** [comment]
Another direction is to play off the boot theme used at RubyConf.

![14316-ynkp4fgm_200x200](https://cloud.githubusercontent.com/assets/25094/16474976/6cd9ab52-3e40-11e6-8127-5727eb58ce9c.jpg)

**Comment by AaronLasseigne** [comment]
![dallas-ruby](https://cloud.githubusercontent.com/assets/297205/16971692/80555aea-4deb-11e6-8f77-6927a909044d.png)

This logo came from Benjamin Walker.

**Comment by AaronLasseigne** [comment]
I'm closing this and declaring Ben's logo the new DRB logo.

**Comment by mattr-** [comment]
:+1:
